// flow-typed signature: e3833c7259bc64e06f82a5fefab6b344
// flow-typed version: <<STUB>>/lien_v^2.3.0/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lien'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'lien' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'lien/example/index' {
  declare module.exports: any;
}

declare module 'lien/example/login' {
  declare module.exports: any;
}

declare module 'lien/example/secure' {
  declare module.exports: any;
}

declare module 'lien/lib/index' {
  declare module.exports: any;
}

declare module 'lien/lib/to-buffer' {
  declare module.exports: any;
}

declare module 'lien/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'lien/example/index.js' {
  declare module.exports: $Exports<'lien/example/index'>;
}
declare module 'lien/example/login.js' {
  declare module.exports: $Exports<'lien/example/login'>;
}
declare module 'lien/example/secure.js' {
  declare module.exports: $Exports<'lien/example/secure'>;
}
declare module 'lien/lib/index.js' {
  declare module.exports: $Exports<'lien/lib/index'>;
}
declare module 'lien/lib/to-buffer.js' {
  declare module.exports: $Exports<'lien/lib/to-buffer'>;
}
declare module 'lien/test/index.js' {
  declare module.exports: $Exports<'lien/test/index'>;
}
