// flow-typed signature: d9a481f3c0510b46da316919ea2c1d88
// flow-typed version: <<STUB>>/rx_v^4.1.0/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rx'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'rx' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rx/dist/rx.aggregates' {
  declare module.exports: any;
}

declare module 'rx/dist/rx.aggregates.min' {
  declare module.exports: any;
}

declare module 'rx/dist/rx.all.compat' {
  declare module.exports: any;
}

declare module 'rx/dist/rx.all.compat.min' {
  declare module.exports: any;
}

declare module 'rx/dist/rx.all' {
  declare module.exports: any;
}

declare module 'rx/dist/rx.all.min' {
  declare module.exports: any;
}

declare module 'rx/dist/rx.async.compat' {
  declare module.exports: any;
}

declare module 'rx/dist/rx.async.compat.min' {
  declare module.exports: any;
}

declare module 'rx/dist/rx.async' {
  declare module.exports: any;
}

declare module 'rx/dist/rx.async.min' {
  declare module.exports: any;
}

declare module 'rx/dist/rx.backpressure' {
  declare module.exports: any;
}

declare module 'rx/dist/rx.backpressure.min' {
  declare module.exports: any;
}

declare module 'rx/dist/rx.binding' {
  declare module.exports: any;
}

declare module 'rx/dist/rx.binding.min' {
  declare module.exports: any;
}

declare module 'rx/dist/rx.coincidence' {
  declare module.exports: any;
}

declare module 'rx/dist/rx.coincidence.min' {
  declare module.exports: any;
}

declare module 'rx/dist/rx.compat' {
  declare module.exports: any;
}

declare module 'rx/dist/rx.compat.min' {
  declare module.exports: any;
}

declare module 'rx/dist/rx.core.binding' {
  declare module.exports: any;
}

declare module 'rx/dist/rx.core.binding.min' {
  declare module.exports: any;
}

declare module 'rx/dist/rx.core' {
  declare module.exports: any;
}

declare module 'rx/dist/rx.core.min' {
  declare module.exports: any;
}

declare module 'rx/dist/rx.core.testing' {
  declare module.exports: any;
}

declare module 'rx/dist/rx.core.testing.min' {
  declare module.exports: any;
}

declare module 'rx/dist/rx.experimental' {
  declare module.exports: any;
}

declare module 'rx/dist/rx.experimental.min' {
  declare module.exports: any;
}

declare module 'rx/dist/rx.joinpatterns' {
  declare module.exports: any;
}

declare module 'rx/dist/rx.joinpatterns.min' {
  declare module.exports: any;
}

declare module 'rx/dist/rx' {
  declare module.exports: any;
}

declare module 'rx/dist/rx.lite.compat' {
  declare module.exports: any;
}

declare module 'rx/dist/rx.lite.compat.min' {
  declare module.exports: any;
}

declare module 'rx/dist/rx.lite.extras.compat' {
  declare module.exports: any;
}

declare module 'rx/dist/rx.lite.extras.compat.min' {
  declare module.exports: any;
}

declare module 'rx/dist/rx.lite.extras' {
  declare module.exports: any;
}

declare module 'rx/dist/rx.lite.extras.min' {
  declare module.exports: any;
}

declare module 'rx/dist/rx.lite' {
  declare module.exports: any;
}

declare module 'rx/dist/rx.lite.min' {
  declare module.exports: any;
}

declare module 'rx/dist/rx.min' {
  declare module.exports: any;
}

declare module 'rx/dist/rx.sorting' {
  declare module.exports: any;
}

declare module 'rx/dist/rx.sorting.min' {
  declare module.exports: any;
}

declare module 'rx/dist/rx.testing' {
  declare module.exports: any;
}

declare module 'rx/dist/rx.testing.min' {
  declare module.exports: any;
}

declare module 'rx/dist/rx.time' {
  declare module.exports: any;
}

declare module 'rx/dist/rx.time.min' {
  declare module.exports: any;
}

declare module 'rx/dist/rx.virtualtime' {
  declare module.exports: any;
}

declare module 'rx/dist/rx.virtualtime.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rx/dist/rx.aggregates.js' {
  declare module.exports: $Exports<'rx/dist/rx.aggregates'>;
}
declare module 'rx/dist/rx.aggregates.min.js' {
  declare module.exports: $Exports<'rx/dist/rx.aggregates.min'>;
}
declare module 'rx/dist/rx.all.compat.js' {
  declare module.exports: $Exports<'rx/dist/rx.all.compat'>;
}
declare module 'rx/dist/rx.all.compat.min.js' {
  declare module.exports: $Exports<'rx/dist/rx.all.compat.min'>;
}
declare module 'rx/dist/rx.all.js' {
  declare module.exports: $Exports<'rx/dist/rx.all'>;
}
declare module 'rx/dist/rx.all.min.js' {
  declare module.exports: $Exports<'rx/dist/rx.all.min'>;
}
declare module 'rx/dist/rx.async.compat.js' {
  declare module.exports: $Exports<'rx/dist/rx.async.compat'>;
}
declare module 'rx/dist/rx.async.compat.min.js' {
  declare module.exports: $Exports<'rx/dist/rx.async.compat.min'>;
}
declare module 'rx/dist/rx.async.js' {
  declare module.exports: $Exports<'rx/dist/rx.async'>;
}
declare module 'rx/dist/rx.async.min.js' {
  declare module.exports: $Exports<'rx/dist/rx.async.min'>;
}
declare module 'rx/dist/rx.backpressure.js' {
  declare module.exports: $Exports<'rx/dist/rx.backpressure'>;
}
declare module 'rx/dist/rx.backpressure.min.js' {
  declare module.exports: $Exports<'rx/dist/rx.backpressure.min'>;
}
declare module 'rx/dist/rx.binding.js' {
  declare module.exports: $Exports<'rx/dist/rx.binding'>;
}
declare module 'rx/dist/rx.binding.min.js' {
  declare module.exports: $Exports<'rx/dist/rx.binding.min'>;
}
declare module 'rx/dist/rx.coincidence.js' {
  declare module.exports: $Exports<'rx/dist/rx.coincidence'>;
}
declare module 'rx/dist/rx.coincidence.min.js' {
  declare module.exports: $Exports<'rx/dist/rx.coincidence.min'>;
}
declare module 'rx/dist/rx.compat.js' {
  declare module.exports: $Exports<'rx/dist/rx.compat'>;
}
declare module 'rx/dist/rx.compat.min.js' {
  declare module.exports: $Exports<'rx/dist/rx.compat.min'>;
}
declare module 'rx/dist/rx.core.binding.js' {
  declare module.exports: $Exports<'rx/dist/rx.core.binding'>;
}
declare module 'rx/dist/rx.core.binding.min.js' {
  declare module.exports: $Exports<'rx/dist/rx.core.binding.min'>;
}
declare module 'rx/dist/rx.core.js' {
  declare module.exports: $Exports<'rx/dist/rx.core'>;
}
declare module 'rx/dist/rx.core.min.js' {
  declare module.exports: $Exports<'rx/dist/rx.core.min'>;
}
declare module 'rx/dist/rx.core.testing.js' {
  declare module.exports: $Exports<'rx/dist/rx.core.testing'>;
}
declare module 'rx/dist/rx.core.testing.min.js' {
  declare module.exports: $Exports<'rx/dist/rx.core.testing.min'>;
}
declare module 'rx/dist/rx.experimental.js' {
  declare module.exports: $Exports<'rx/dist/rx.experimental'>;
}
declare module 'rx/dist/rx.experimental.min.js' {
  declare module.exports: $Exports<'rx/dist/rx.experimental.min'>;
}
declare module 'rx/dist/rx.joinpatterns.js' {
  declare module.exports: $Exports<'rx/dist/rx.joinpatterns'>;
}
declare module 'rx/dist/rx.joinpatterns.min.js' {
  declare module.exports: $Exports<'rx/dist/rx.joinpatterns.min'>;
}
declare module 'rx/dist/rx.js' {
  declare module.exports: $Exports<'rx/dist/rx'>;
}
declare module 'rx/dist/rx.lite.compat.js' {
  declare module.exports: $Exports<'rx/dist/rx.lite.compat'>;
}
declare module 'rx/dist/rx.lite.compat.min.js' {
  declare module.exports: $Exports<'rx/dist/rx.lite.compat.min'>;
}
declare module 'rx/dist/rx.lite.extras.compat.js' {
  declare module.exports: $Exports<'rx/dist/rx.lite.extras.compat'>;
}
declare module 'rx/dist/rx.lite.extras.compat.min.js' {
  declare module.exports: $Exports<'rx/dist/rx.lite.extras.compat.min'>;
}
declare module 'rx/dist/rx.lite.extras.js' {
  declare module.exports: $Exports<'rx/dist/rx.lite.extras'>;
}
declare module 'rx/dist/rx.lite.extras.min.js' {
  declare module.exports: $Exports<'rx/dist/rx.lite.extras.min'>;
}
declare module 'rx/dist/rx.lite.js' {
  declare module.exports: $Exports<'rx/dist/rx.lite'>;
}
declare module 'rx/dist/rx.lite.min.js' {
  declare module.exports: $Exports<'rx/dist/rx.lite.min'>;
}
declare module 'rx/dist/rx.min.js' {
  declare module.exports: $Exports<'rx/dist/rx.min'>;
}
declare module 'rx/dist/rx.sorting.js' {
  declare module.exports: $Exports<'rx/dist/rx.sorting'>;
}
declare module 'rx/dist/rx.sorting.min.js' {
  declare module.exports: $Exports<'rx/dist/rx.sorting.min'>;
}
declare module 'rx/dist/rx.testing.js' {
  declare module.exports: $Exports<'rx/dist/rx.testing'>;
}
declare module 'rx/dist/rx.testing.min.js' {
  declare module.exports: $Exports<'rx/dist/rx.testing.min'>;
}
declare module 'rx/dist/rx.time.js' {
  declare module.exports: $Exports<'rx/dist/rx.time'>;
}
declare module 'rx/dist/rx.time.min.js' {
  declare module.exports: $Exports<'rx/dist/rx.time.min'>;
}
declare module 'rx/dist/rx.virtualtime.js' {
  declare module.exports: $Exports<'rx/dist/rx.virtualtime'>;
}
declare module 'rx/dist/rx.virtualtime.min.js' {
  declare module.exports: $Exports<'rx/dist/rx.virtualtime.min'>;
}
declare module 'rx/index' {
  declare module.exports: $Exports<'rx'>;
}
declare module 'rx/index.js' {
  declare module.exports: $Exports<'rx'>;
}
