// flow-typed signature: 3c7175f9706cf743ee23814c75e1b856
// flow-typed version: <<STUB>>/youtube-api_v^2.0.8/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'youtube-api'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'youtube-api' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'youtube-api/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'youtube-api/lib/index.js' {
  declare module.exports: $Exports<'youtube-api/lib/index'>;
}
